import { useMetamask } from "@thirdweb-dev/react";
import Head from "next/head";
import React from "react";

type LoginProps = {};

const Login: React.FC<LoginProps> = () => {
  const connectWithMetamask = useMetamask();

  return (
    <>
      <div className=" min-h-screen flex flex-col items-center justify-center text-center">
        <Head>
          <title>CRYPTO LOTTERY</title>
          <meta name="description" content="Generated by create next app" />
          <link
            rel="icon"
            href="https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Ethereum_logo_2014.svg/1257px-Ethereum_logo_2014.svg.png"
          />
        </Head>
        <div className="flex flex-col items-center mb-10">
          <img
            src="https://c.tenor.com/zyUn_DgNXyUAAAAd/eth-etherum.gif"
            alt=""
            className="rounded-full h-56 w-56 mb-10"
          />
          <h1 className="text-6xl text-white font-bold">CRYPTO LOTTERY</h1>
          <h2 className="text-white">
            Get Started by logging in with your MetaMask
          </h2>
          <button
            onClick={connectWithMetamask}
            className="bg-white px-8 py-5 mt-10 rounded-lg shadow-lg font-bold"
          >
            Login with Metamask
          </button>
        </div>
      </div>
    </>
  );
};
export default Login;
